#!/bin/sh

die () {
    die_with_status 1 $1
}

die_with_status () {
    STATUS=$1
    shift
    echo "$*"
    exit "$STATUS"
}

usage() {
    echo "$USAGE"
    exit 1
}

HELP=0
PROJECT_DIR=`pwd`
CONFIG_FILE=".stick.cfg"

# fixup the project dir if possible
while [ ! -f "$PROJECT_DIR/$CONFIG_FILE" ]; do
    PROJECT_DIR=$PROJECT_DIR/..
    if [ ! -d "$PROJECT_DIR" ]; then
        # restore pwd as project dir and break
        PROJECT_DIR=`pwd`
        break;
    fi
done

ISSUES_DIR=$PROJECT_DIR/issues
STATE_DIR=$PROJECT_DIR/state
STATE_LINK_BASE=../../issues
DEFAULT_STATE=open
DEFAULT_EXT=.md

