#!/bin/sh
set -e

USAGE="\
Simple Tickets

Print the state of a ticket

Usage:
    stick state <ticket-id>
"
SCRIPT=`readlink -f $0`
DIR=`dirname $SCRIPT`

. $DIR/stick-env.sh

while [ $# -gt 0 ]; do
    ARG=$1
    case "$ARG" in
    --help|-h)
        HELP=1
        ;;
    --*)
        die "unrecognised option: $ARG" ;;
    *)
        TICKET_ID=$1
        ;;
    esac
    shift
done

if [ $HELP -eq 1 ] || [ -z $TICKET_ID ]; then
    usage
fi

file=$TICKET_ID$DEFAULT_EXT
file_path=$ISSUES_DIR/$file
if [ ! -f "$file_path" ]; then
    die "Invalid ticket number"
fi

for state in $STATES; do
    link=$state/$file
    if [ -f "$link" ]; then
        echo "$(basename $(dirname $link))"
        exit 0
    fi
done

# not found
exit 1
