#!/bin/sh
set -e

USAGE="\
Simple Tickets

create a new ticket

Usage:
    stick new [options] <ticket-id>

Options:
    -t, --title TITLE   Set the ticket title
"
SCRIPT=`readlink -f $0`
DIR=`dirname $SCRIPT`

. $DIR/stick-env.sh

while [ $# -gt 0 ]; do
    ARG=$1
    case "$ARG" in
    --help|-h)
        HELP=1
        ;;
    --title|-t)
        shift
        TITLE=$1
        ;;
    --title=*)
        TITLE=${1#*=}
        ;;
    --*)
        die "unrecognised option: $ARG" ;;
    *)
        TICKET_ID=$1
        ;;
    esac
    shift
done

if [ $HELP -eq 1 ] || [ -z $TICKET_ID ]; then
    usage
fi


FILE=$TICKET_ID$DEFAULT_EXT
FILE_PATH=$ISSUES_DIR/$FILE
if [ -z "$TITLE" ]; then
    TITLE="Unnamed ticket"
fi

if [ -f "$FILE_PATH" ]; then
    die "Ticket already present"
fi

mkdir -p "$ISSUES_DIR" "$STATE_DIR/$DEFAULT_STATE"
cat >"$FILE_PATH" <<EOF
$(echo "$TICKET_ID" | tr '[:lower:]' '[:upper:]') $TITLE
===================
EOF

cd "$STATE_DIR/$DEFAULT_STATE"
ln -s "$STATE_LINK_BASE/$FILE" $FILE

echo "Ticket $TICKET_ID created"
