#!/bin/sh
set -e

USAGE="\
Simple Tickets

List tickets

Usage:
    stick list [options]

Options:
    -s, --state STATE   List only tickets in the specified state
"
SCRIPT=`readlink -f $0`
DIR=`dirname $SCRIPT`

. $DIR/stick-env.sh

while [ $# -gt 0 ]; do
    ARG=$1
    case "$ARG" in
    --help|-h)
        HELP=1
        ;;
    --state|-s)
        shift
        STATE=$1
        ;;
    --state=*)
        STATE=${1#*=}
        ;;
    --*)
        die "unrecognised option: $ARG" ;;
    esac
    shift
done

if [ "$HELP" -eq 1 ]; then
    usage
fi

list_state_issues() {
    state="$1"
    if [ ! -d "$STATE_DIR/$state" ]; then
        die "unknown state: $state"
    fi
    for file in $STATE_DIR/$state/*; do
        print_ticket_info "$file" "$state"
    done
}

if [ -z "$STATE" ]; then
    for state in $STATE_DIR/*; do
        list_state_issues $(basename "$state")
    done
else
    list_state_issues "$STATE"
fi
