#!/bin/sh
set -e

USAGE="\
Simple Tickets, create a new ticket

Usage:
    stick new [options] <ticket-id>

Options:
    -t, --title TITLE   Set the ticket title
"

usage() {
    echo "$USAGE"
    exit 1
}

TOTAL_ARGC=$#
test $TOTAL_ARGC -gt 0 || usage

while [ $# -gt 0 ]; do
    ARG=$1
    case "$ARG" in
    --help|-h)
        HELP=1
        ;;
    --)
        shift
        break
        ;;
    esac
    shift
done

if test $HELP -eq 1; then
    usage
fi


TICKET_ID=$1
SCRIPT=`realpath $0`
DIR=`dirname $SCRIPT`
. $DIR/_stick-env

echo "DONE!"
